### PR TITLE
Mentor Registration added

### PR DESCRIPTION
**Pull request by aritropc**
Added Mentor Registration section with the link to the [**registration form**](http://bit.ly/dsciemma)

Here is how it looks like
image

Please check my PR @mahakmakharia

### CODE REVIEW

**Comment by mahakmakharia** [comment]
Looks good, will check and merge soon :)

**Comment by mahakmakharia** [comment]
@aritropc Add this section above the contact us section and not below it, once you do that let me know

**Comment by aritropc** [comment]
Sorry for the late reply. Shall I then change the bg color of the contact section, as they're alternately white and grey? @mahakmakharia

**Comment by mahakmakharia** [comment]
@aritropc yes please

**Comment by mahakmakharia** [comment]
@aritropc update?

**Comment by aritropc** [comment]
I've done the required changes. @mahakmakharia

**Pull request merged**
