### PR TITLE
Added the first half of projects.html

### PR DESCRIPTION
**Pull request by the-agarwal01**

### CODE REVIEW

**Comment by mahakmakharia** [comment]
share a screenshot please @the-agarwal01

**Comment by the-agarwal01** [comment]
first half

**Comment by the-agarwal01** [comment]
@mahakmakharia above is the ss of the first half of the page.

**Comment by mahakmakharia** [comment]
Looks good! Great work :)

**Comment by the-agarwal01** [comment]
Thanks:)

**Pull request merged**
