### PR TITLE
feat: create a section for volunteers

### LINKED ISSUE #29: Create a section for volunteers in the team.html
Make a new section named volunteers for showing the details, namely, the name and designation of all the volunteers in our team.

### PR DESCRIPTION
**Pull request by pallavithakare28**
# Description
I have created a volunteer section in team.html using a card that flips vertically.

Fixes #29 

# Proposed changes
- Code
- User Interface

# Mocks
 - Front View
Volunteers

 - Back View
Volunteers-2

### CODE REVIEW

**Comment by pallavithakare28** [comment]
Hey @mahakmakharia , I have tried to use different designs(like contact chips, flip box) but it does not look that much effective. So I decided to come up with cards only which flip vertically. Please let me know if you require any changes to the design.

**Comment by mahakmakharia** [comment]
Looks good to me, are you up for adding the details of our team members?

**Comment by pallavithakare28** [comment]
@mahakmakharia Yes, Sure but it'll take little bit time for me as I am busy with exams. I hope you consider it.

**Comment by mahakmakharia** [comment]
Yes definitely, will send you a sheet by sunday, you can ask someone else to work with you as well :)

**Comment by pallavithakare28** [comment]
@mahakmakharia Ok :)

**Comment by mahakmakharia** [comment]
https://docs.google.com/spreadsheets/d/11fySHBTeYvaMt7dkYzqASIVjVhh0U_sfnYUT6B2tm7w/edit?usp=sharing

Hey, sorry about the delay, use this link

**Comment by pallavithakare28** [comment]
Hey @mahakmakharia, I'm working on it. :)

**Pull request closed without merging**
